### ISSUE TITLE
NPM Module

### ISSUE THREAD

**Issue by adampickeral** [rackerlabs/canon-react#10]
Should be available via NPM

The bundled js should also be part of the module.

**Comment by adampickeral** [comment]
https://github.com/rackerlabs/canon-react/issues/18

React should be required in each file that needs it. We should modify the build system to allow react being supplied as a global variable or not.

**Comment by adampickeral** [comment]
place the built js in a /dist directory and store in version control

**Comment by bradgignac** [comment]
BTW, if you are only publishing to NPM, you can leave built files out of source control and build as part of the pre-publish command.

**Comment by adampickeral** [comment]
oh cool, thanks!

**Comment by SethNute** [comment]
I put together a quick prepublish script and was about to start a PR around this but I don't have access to this repo it seems. Do I need to be explicitly added to RackerLabs?

**Comment by bradgignac** [comment]
@SethNute Leaving my IRC comment here as well. It would be nice to have access to the raw source files. It looks like the file indicated by the `main` field of package.json includes React and is minified. I want to control my own version of React, and the minified file makes debugging hard. My build system already supports CJS, so we don't really want prebuilt files.
