### ISSUE TITLE
Peer dependencies out of date

### ISSUE THREAD

**Issue by steveortiz** [rackerlabs/canon-react#107]
I was just wondering if you had looked into updating the peer dependencies in canon-react to support React v15

https://github.com/rackerlabs/canon-react/blob/master/package.json#L45-L46

**Comment by wpwood** [comment]
I believe that Canon-React is committed to supporting the current and previous versions of React, which means we have to ship with 0.14.8 until v16 (or whatever they decide to call it) is released.

**Comment by steveortiz** [comment]
@wpwood Thank you for the insight.  I will close this issue.
