### ISSUE TITLE
Action Dropdown

### ISSUE THREAD

**Issue by adampickeral** [rackerlabs/canon-react#15]
http://rackerlabs.github.io/canon/ui-components/#dropdowns

**Comment by jdrush89** [comment]
I started working on this last hackday, will likely continue for hack week

**Comment by Jigarsolanki** [comment]
@jdrush89 Could you please update this issue briefly with your approach?

**Comment by jdrush89** [comment]
The ActionMenu component will create a container on the document in which renders an ActionMenuList into.  The ActionMenu passes its children to the ActionMenuList (the list items).  In addition, it renders a button whose content is set through props (could be a cog menu, action button, etc).  The menu list takes the button element as a target prop which it uses to do positioning.  The list items take as props events to fire when clicked.

**Comment by bradgignac** [comment]
@jdrush89 How do you plan to handle position inside elements with `overflow: hidden`? Typically, we've had to render these components into the body rather than directly in the DOM. Similarly, how do you plan to handle cases in which the dropdown need to be displayed above the button?

**Comment by jdrush89** [comment]
the actionMenuList will be rendered on a container on the document in all cases, similar to the tooltip we use today https://github.com/racker/reach/blob/master/cloudkick/webapp/site_media/js/rs/tooltip/tooltip.jsx#L88.  It uses absolute positioning based off the target's position.  First implementation will probably be dumb and always display under the target, but it shouldn't be too difficult to detect if the menu won't fit below and display it above instead in componentDidUpdate, similar to the repositioning I did for tooltips in this PR https://github.com/racker/reach/pull/12772

**Comment by bradgignac** [comment]
Sounds good. The only suggestion I would make is to debounce the scroll handler and adding support for window resizing. Also, you might be interested in a library like http://github.hubspot.com/tether.
