### ISSUE TITLE
Popover

### ISSUE THREAD

**Issue by adampickeral** [rackerlabs/canon-react#16]
http://rackerlabs.github.io/canon/ui-components/#popover

# Design Considerations
As with most of the components in this library, the design for the popover is intended to be very dumb, i.e. any logic to display data within the popover is up to the consumer. Deciding when to hide the popover after some action is completed is also the responsibility of the consumer, but a callback is provided within this design. Showing and hiding the popover based on the click of a trigger or clicks outside of the popover is handled by the components in this design.

## Components
`PopoverTrigger`
`Popover`
`PopoverBody`
`PopoverFooter`

### `PopoverTrigger`
The `PopoverTrigger` is used to specify the component that will trigger the rendering of the popover as well as the popover to be rendered.

###### Example
```javascript
<PopoverTrigger placement='right' popover={<SomePopover/>}>
  <Button>Click Here</Button>
</PopoverTrigger>
```
The `PopoverTrigger` handles rendering the popover whenever the trigger is clicked, as well as hiding the popover whenever a click outside of the popover occurs, the `Escape` key is pressed, or the hide callback is invoked by the popover.

The 'placement' prop is used to position the popover relative to the trigger. This prop is also passed to the popover when it is rendered. The accepted values are:
* `'right'`
* `'left'`
* `'bottom-right'`
* `'bottom-left'`

The trigger itself is rendered with an `onClick` prop that is configured by the trigger which in decides when to show or hide the popover.

The `popover` prop is the actual popover component that will be displayed when the trigger is clicked. This component is rendered with a `placement` prop and a `hideCallback` prop. The `placement` prop must be passed down to the `Popover` component in order to properly position the arrow of the popover. The `hideCallback` prop should be called whenever some form processing has completed and the popover should be hidden, or as the value to the `onClick` prop of a cancel link.

### `Popover`
The `Popover` class renders the outer markup of a popover, as well as the arrow of the popover. It accepts a `placement` prop which is used to determine the position of the arrow relative to the target at  which the popover will be pointing. The values accepted are the same as those of the `PopoverTrigger`.

### `PopoverBody` and `PopoverFooter`
These components should be used together when displaying a popover that will do some sort of form processing. If a popover is only being used to display information, these components aren't needed. These components simple wrap their children in the appropriate markup for a popover form. They don't do any special processing of the children to be rendered. Any change of state of buttons rendered in the footer is the responsibility of the consumer to update. This allows for greater flexibility of what the body and footer can be composed of.

###### Render the Trigger
```javascript
<PopoverTrigger placement='right' popover={<UpdateNamePopover/>}>
  <Button>Update Name</Button>
</PopoverTrigger>
```

###### Popover
```javascript
var UpdateNamePopover = React.createClass({
  render: function () {
    return (
      <Popover placement={this.props.placement}>
        <PopoverBody>
          <form>
           <label>Name</label>
           <input type='text' />
          </form>
        </PopoverBody>
        <PopoverFooter>
          <Button type='primary' onClick={this._processSave}>Save</Button>
          <Button type='link' onClick={this.props.hideCallback}>Cancel</Button>
          <ProcessingIndicator hidden={true} />
        </PopoverFooter>
      </Popover>
    );
  },

  _processSave: function () {
    // set some state to toggle button states for processing of action
    // perform some action, maybe through stores
    // on successful action completion, invoke this.props.hideCallback
  }
});
```

**Comment by adampickeral** [comment]
Implementation is in the PR https://github.com/rackerlabs/canon-react/pull/27

**Comment by Jigarsolanki** [comment]
Looks good. Couple of thoughts:

* When you render PopoverTrigger component, not necessarily you'd have the data that popover needs. How would you achieve that in here? for instance, we have ```withModel``` and ```withData``` methods in Reach.
* I know reach-bootstrap does that but I'm a fan of passing components as a param. Seems really strange to me (```<PopoverTrigger placement='right' popover={<UpdateNamePopover/>}>````). 
What are the challenges achieving below? 
 ```javascript 
<UpdateNamePopover placement='right'> 
 <Button>Update Name</Button>
</UpdateNamePopover>
```
I think the obvious answer is inheritance but wanted to know your opinions and thought on that. 

* Does popover trigger need to have only one element? or should it support multiple?

**Comment by jdrush89** [comment]
Awesome!  You think the PopoverTrigger trigger logic should be generalized in the future into an OverlayTrigger and used elsewhere like ActionMenus?

**Comment by jdrush89** [comment]
@Jigarsolanki I think the trigger having only one element is simpler, you only have to worry about about maintaining one click handler.  You can always wrap your multiple elements in one container.

**Comment by adampickeral** [comment]
@jdrush89 yes i definitely think the PopoverTrigger can be generalized to support other types of overlays

@Jigarsolanki we could make the trigger support multiple elements, but i can't think of a use case for that, can you?

for loading data into the popover, you could do this a few different ways. the easiest way is to use props to pass the data in. if you need something loaded dynamically, you can use a store, or whatever data-loading mechanism your application currently uses to get the data. the actual popover itself will be created and rendered every time the popover is displayed. With this, you can load any data in the popover that you don't have on initial render in a `componentWillMount` method on your popover. Here's my simple example in the control panel where I'm just passing the stack in as a prop https://github.com/racker/reach/pull/13473/files#diff-cc9f62f7119cd16587c6e21609efefc7R77

To the last point about not using props to specify the component, I think the only way to achieve that is through inheritance. Inheritance is great and with tools like babel teams can start using it today, but for teams like the control panel, we aren't quite there yet, so the only way to implement this right now is through composition.
