### ISSUE TITLE
Exposing Tethering low level parameters in Popovers

### ISSUE THREAD

**Issue by MACSkeptic** [rackerlabs/canon-react#77]
Recently we implemented a popover in Janus that looks like this:

![image](https://cloud.githubusercontent.com/assets/53897/13319353/5f6d87b8-dbc1-11e5-94aa-026904b6a5b4.png)

We couldn't make that work with the exposed tethering abstractions from https://github.com/rackerlabs/canon-react/blob/master/src/Popover.jsx#L105.

The positioning on the screenshot is done by tricking the algorithm with a absolutely positioned ghost element.

I believe it would be possible to do that if we could set the tether config to:

```
     attachment: 'top left',
     targetAttachment: 'bottom left',
```

That said, I'd expect more scenarios could also benefit from this. I think the abstract tethering named configurations are good, but would be great if we could access/influence the raw settings for Popover positioning.

**Comment by adampickeral** [comment]
resolved by #97
